### ISSUE TITLE
Propuesta de árbol de contenidos   &   Newsletter mensual

### ISSUE THREAD

**Issue by xaniag** [aurora-mareviv/sedar#5]
Anexo documento word con propuesta de 
-estructura 
-secciones 
-newsletter.

[Estructura de la página.docx](https://github.com/aurora-mareviv/sedar/files/1652188/Estructura.de.la.pagina.docx)

**Comment by aurora-mareviv** [comment]
Jo, está muy completo el árbol de contenidos que propones! genial!  
✏️ 
Me pongo a ello, tiene mucha "chicha" para elaborar. No sé si podré cumplirlo al 100% pero iré haciendo una muestra para que todos lo vayan viendo en el boceto de página.

**Comment by aurora-mareviv** [comment]
He actualizado el árbol de contenidos según tus sugerencias, además he creado las "páginas índice" (`index.html`) para cada sección del menú.   

De esta forma si alguien tiene una idea acerca de una página concreta de este árbol la podemos esbozar.  

Échale un vistazo en:   https://anescalc.github.io/sedar

**Comment by aurora-mareviv** [comment]
Cierro la issue, tras la reunión. Saludos!

**Comment by aurora-mareviv** [comment]
Cierro la issue, tras la reunión. **Saludos!** 😄
